# Dockerfile for hazyresearch/snorkel-dev
# to be used with DockerBuild/ also by Travis CI
#
# $ docker build -t hazyresearch/snorkel-dev - <Dockerfile-dev
#
# Optional:
# $ docker push hazyresearch/snorkel-dev

FROM hazyresearch/snorkel
MAINTAINER deepdive-dev@googlegroups.com

# Use runipy to run Jupyter/IPython notebooks from command-line
RUN pip install runipy

WORKDIR snorkel

# Install all dependencies as per our README
RUN test -e parser/corenlp.sh || ./install-parser.sh
RUN [ -x deepdive/bin/mindbender ] || bash -euc 'PREFIX="$PWD"/deepdive bash <(curl -fsSL git.io/getdeepdive || wget -qO- git.io/getdeepdive) deepdive_from_release'
RUN pip install -r requirements.txt

