# Dockerfile for hazyresearch/snorkel-dev
# to be used with DockerBuild/ also by Travis CI
#
# $ docker build -t hazyresearch/snorkel-dev - <Dockerfile-dev
#
# Optional:
# $ docker push hazyresearch/snorkel-dev

FROM hazyresearch/snorkel
MAINTAINER deepdive-dev@googlegroups.com

# Use runipy to run Jupyter/IPython notebooks from command-line
RUN pip install runipy

WORKDIR snorkel
