from typing import Dict

from setuptools import find_packages, setup

# version.py defines the VERSION and VERSION_SHORT variables.
# We use exec here so we don't import snorkel.
VERSION: Dict[str, str] = {}
with open("snorkel/version.py", "r") as version_file:
    exec(version_file.read(), VERSION)

# Use README.md as the long_description for the package
with open("README.md", "r") as readme_file:
    long_description = readme_file.read()

setup(
    name="snorkel",
    version=VERSION["VERSION"],
    url="https://github.com/snorkel-team/snorkel",
    description="A system for quickly generating training data with weak supervision",
    long_description_content_type="text/markdown",
    long_description=long_description,
    license="Apache License 2.0",
    classifiers=[
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
    ],
    project_urls={
        "Homepage": "https://snorkel.org",
        "Source": "https://github.com/snorkel-team/snorkel/",
        "Bug Reports": "https://github.com/snorkel-team/snorkel/issues",
        "Citation": "https://doi.org/10.14778/3157794.3157797",
    },
    packages=find_packages(exclude=("test*",)),
    include_package_data=True,
    install_requires=[
        "absl-py==1.2.0",
        "attrs==22.1.0",
        "black==22.6.0",
        "blis==0.7.8",
        "cachetools==4.2.4",
        "catalogue==2.0.8",
        "certifi==2022.6.15",
        "charset-normalizer==2.0.12",
        "click==8.0.4",
        "cloudpickle==2.1.0",
        "contextvars==2.4",
        "coverage==6.2",
        "cymem==2.0.6",
        "dask==2021.3.0",
        "decorator==4.4.2",
        "dill==0.3.4",
        "distlib==0.3.5",
        "distributed==2021.3.0",
        "filelock==3.4.1",
        "flake8==5.0.0",
        "fsspec==2022.1.0",
        "google-auth==2.9.1",
        "google-auth-oauthlib==0.4.6",
        "grpcio==1.48.0",
        "HeapDict==1.0.1",
        "idna==3.3",
        "immutables==0.18",
        "importlib-metadata==4.2.0",
        "importlib-resources==5.4.0",
        "isort==5.10.1",
        "Jinja2==3.0.3",
        "joblib==1.1.0",
        "langcodes==3.3.0",
        "locket==1.0.0",
        "Markdown==3.3.4",
        "MarkupSafe==2.0.1",
        "mccabe==0.7.0",
        "more-itertools==8.13.0",
        "msgpack==1.0.4",
        "munkres==1.1.4",
        "murmurhash==1.0.7",
        "mypy==0.760",
        "mypy-extensions==0.4.3",
        "networkx==2.5.1",
        "numpy==1.19.5",
        "oauthlib==3.2.0",
        "packaging==21.3",
        "pandas==1.1.5",
        "partd==1.2.0",
        "pathspec==0.9.0",
        "pathy==0.6.2",
        "platformdirs==2.4.0",
        "pluggy==0.13.1",
        "preshed==3.0.6",
        "protobuf==3.19.4",
        "psutil==5.9.1",
        "py==1.11.0",
        "py4j==0.10.9",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "pycodestyle==2.9.0",
        "pydantic==1.9.1",
        "pydocstyle==6.1.1",
        "pyflakes==2.5.0",
        "pyparsing==3.0.9",
        "pyspark==3.1.2",
        "pytest==5.4.3",
        "pytest-cov==3.0.0",
        "pytest-doctestplus==0.9.0",
        "python-dateutil==2.8.2",
        "pytz==2022.1",
        "PyYAML==6.0",
        "requests==2.27.1",
        "requests-oauthlib==1.3.1",
        "rsa==4.9",
        "scikit-learn==0.24.2",
        "scipy==1.5.4",
        "six==1.16.0",
        "smart-open==5.2.1",
        "snowballstemmer==2.2.0",
        "sortedcontainers==2.4.0",
        "spacy==3.4.1",
        "spacy-legacy==3.0.9",
        "spacy-loggers==1.0.3",
        "srsly==2.4.4",
        "tblib==1.7.0",
        "tensorboard==2.9.1",
        "tensorboard-data-server==0.6.1",
        "tensorboard-plugin-wit==1.8.1",
        "thinc==8.1.0",
        "threadpoolctl==3.1.0",
        "toml==0.10.2",
        "tomli==1.2.3",
        "toolz==0.12.0",
        "torch==1.12.0",
        "tornado==6.1",
        "tox==3.25.1",
        "tqdm==4.64.0",
        "typed-ast==1.4.3",
        "typer==0.4.2",
        "typing_extensions==4.1.1",
        "urllib3==1.26.11",
        "virtualenv==20.16.2",
        "wasabi==0.10.1",
        "wcwidth==0.2.5",
        "Werkzeug==2.0.3",
        "zict==2.1.0",
        "zipp==3.6.0",
    ],
    python_requires=">=3.6",
    keywords="machine-learning ai weak-supervision",
)
