from snorkel.map import (  # noqa: F401
    BaseMapper as BaseTransformationFunction,
    LambdaMapper as LambdaTransformationFunction,
    Mapper as TransformationFunction,
    lambda_mapper as transformation_function,
)

"""Base classes for transformation functions.

A transformation function (TF) represents an atomic transformation
to a data point in a data augmentation pipeline. Common examples in
image processing include small image rotations or crops. Snorkel
models data augmentation as a sequence of TFs generated by a policy.
"""
